eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8005
spring:
  application:
    name: api-gateway
  #集成redis配置
  redis:
    host: 192.168.1.191
    port: 6379
#路由
zuul:
  routes:
    # eureka-product: /myProduct/**
    myProduct:
      path: /myProduct/**
      serviceId: eureka-product
    myOrder:
      path: /myOrder/**
      serviceId: eureka-order
  # ignored-patterns:
  # - /**/product/listForOrder
  #全部服务忽略敏感头
  sensitive-headers:
management:
  endpoints:
    web:
      exposure:
        include: routes
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000